/* File: _xxdata_11module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Jul 13 19:31:56 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_xxdata_11_error;
static PyObject *_xxdata_11_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _xxdata_11_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _xxdata_11_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(xxdata_11,XXDATA_11)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,string,double*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,size_t);
extern void F_FUNC_US(helper_open_file,HELPER_OPEN_FILE)(int*,string,size_t);
extern void F_FUNC_US(helper_close_file,HELPER_CLOSE_FILE)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* xxdata_11 *********************************/
static char doc_f2py_rout__xxdata_11_xxdata_11[] = "\
iz0,is1min,is1max,nptnl,nptn,nptnc,iptnla,iptna,iptnca,ncnct,icnctv,iblmx,ismax,dnr_ele,dnr_ams,isppr,ispbr,isstgr,idmax,itmax,ddens,dtev,drcof,lres,lstan,lptn = xxdata_11(iunit,iclass,isdimd,iddimd,itdimd,ndptnl,ndptn,ndptnc,ndcnct)\n\nWrapper for ``xxdata_11``.\
\n\nParameters\n----------\n"
"iunit : input int\n"
"iclass : input int\n"
"isdimd : input int\n"
"iddimd : input int\n"
"itdimd : input int\n"
"ndptnl : input int\n"
"ndptn : input int\n"
"ndptnc : input int\n"
"ndcnct : input int\n"
"\nReturns\n-------\n"
"iz0 : int\n"
"is1min : int\n"
"is1max : int\n"
"nptnl : int\n"
"nptn : rank-1 array('i') with bounds (ndptnl)\n"
"nptnc : rank-2 array('i') with bounds (ndptnl,ndptn)\n"
"iptnla : rank-1 array('i') with bounds (ndptnl)\n"
"iptna : rank-2 array('i') with bounds (ndptnl,ndptn)\n"
"iptnca : rank-3 array('i') with bounds (ndptnl,ndptn,ndptnc)\n"
"ncnct : int\n"
"icnctv : rank-1 array('i') with bounds (ndcnct)\n"
"iblmx : int\n"
"ismax : int\n"
"dnr_ele : string(len=12)\n"
"dnr_ams : float\n"
"isppr : rank-1 array('i') with bounds (isdimd)\n"
"ispbr : rank-1 array('i') with bounds (isdimd)\n"
"isstgr : rank-1 array('i') with bounds (isdimd)\n"
"idmax : int\n"
"itmax : int\n"
"ddens : rank-1 array('d') with bounds (iddimd)\n"
"dtev : rank-1 array('d') with bounds (itdimd)\n"
"drcof : rank-3 array('d') with bounds (isdimd,itdimd,iddimd)\n"
"lres : int\n"
"lstan : int\n"
"lptn : int";
/* extern void F_FUNC_US(xxdata_11,XXDATA_11)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,string,double*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,size_t); */
static PyObject *f2py_rout__xxdata_11_xxdata_11(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,string,double*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iunit = 0;
  PyObject *iunit_capi = Py_None;
  int iclass = 0;
  PyObject *iclass_capi = Py_None;
  int isdimd = 0;
  PyObject *isdimd_capi = Py_None;
  int iddimd = 0;
  PyObject *iddimd_capi = Py_None;
  int itdimd = 0;
  PyObject *itdimd_capi = Py_None;
  int ndptnl = 0;
  PyObject *ndptnl_capi = Py_None;
  int ndptn = 0;
  PyObject *ndptn_capi = Py_None;
  int ndptnc = 0;
  PyObject *ndptnc_capi = Py_None;
  int ndcnct = 0;
  PyObject *ndcnct_capi = Py_None;
  int iz0 = 0;
  int is1min = 0;
  int is1max = 0;
  int nptnl = 0;
  int *nptn = NULL;
  npy_intp nptn_Dims[1] = {-1};
  const int nptn_Rank = 1;
  PyArrayObject *capi_nptn_tmp = NULL;
  int capi_nptn_intent = 0;
  int *nptnc = NULL;
  npy_intp nptnc_Dims[2] = {-1, -1};
  const int nptnc_Rank = 2;
  PyArrayObject *capi_nptnc_tmp = NULL;
  int capi_nptnc_intent = 0;
  int *iptnla = NULL;
  npy_intp iptnla_Dims[1] = {-1};
  const int iptnla_Rank = 1;
  PyArrayObject *capi_iptnla_tmp = NULL;
  int capi_iptnla_intent = 0;
  int *iptna = NULL;
  npy_intp iptna_Dims[2] = {-1, -1};
  const int iptna_Rank = 2;
  PyArrayObject *capi_iptna_tmp = NULL;
  int capi_iptna_intent = 0;
  int *iptnca = NULL;
  npy_intp iptnca_Dims[3] = {-1, -1, -1};
  const int iptnca_Rank = 3;
  PyArrayObject *capi_iptnca_tmp = NULL;
  int capi_iptnca_intent = 0;
  int ncnct = 0;
  int *icnctv = NULL;
  npy_intp icnctv_Dims[1] = {-1};
  const int icnctv_Rank = 1;
  PyArrayObject *capi_icnctv_tmp = NULL;
  int capi_icnctv_intent = 0;
  int iblmx = 0;
  int ismax = 0;
  string dnr_ele = NULL;
  int slen(dnr_ele);
  PyObject *dnr_ele_capi = Py_None;
  double dnr_ams = 0;
  int *isppr = NULL;
  npy_intp isppr_Dims[1] = {-1};
  const int isppr_Rank = 1;
  PyArrayObject *capi_isppr_tmp = NULL;
  int capi_isppr_intent = 0;
  int *ispbr = NULL;
  npy_intp ispbr_Dims[1] = {-1};
  const int ispbr_Rank = 1;
  PyArrayObject *capi_ispbr_tmp = NULL;
  int capi_ispbr_intent = 0;
  int *isstgr = NULL;
  npy_intp isstgr_Dims[1] = {-1};
  const int isstgr_Rank = 1;
  PyArrayObject *capi_isstgr_tmp = NULL;
  int capi_isstgr_intent = 0;
  int idmax = 0;
  int itmax = 0;
  double *ddens = NULL;
  npy_intp ddens_Dims[1] = {-1};
  const int ddens_Rank = 1;
  PyArrayObject *capi_ddens_tmp = NULL;
  int capi_ddens_intent = 0;
  double *dtev = NULL;
  npy_intp dtev_Dims[1] = {-1};
  const int dtev_Rank = 1;
  PyArrayObject *capi_dtev_tmp = NULL;
  int capi_dtev_intent = 0;
  double *drcof = NULL;
  npy_intp drcof_Dims[3] = {-1, -1, -1};
  const int drcof_Rank = 3;
  PyArrayObject *capi_drcof_tmp = NULL;
  int capi_drcof_intent = 0;
  int lres = 0;
  int lstan = 0;
  int lptn = 0;
  static char *capi_kwlist[] = {"iunit","iclass","isdimd","iddimd","itdimd","ndptnl","ndptn","ndptnc","ndcnct",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO:_xxdata_11.xxdata_11",\
    capi_kwlist,&iunit_capi,&iclass_capi,&isdimd_capi,&iddimd_capi,&itdimd_capi,&ndptnl_capi,&ndptn_capi,&ndptnc_capi,&ndcnct_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iunit */
    f2py_success = int_from_pyobj(&iunit,iunit_capi,"_xxdata_11.xxdata_11() 1st argument (iunit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iclass */
    f2py_success = int_from_pyobj(&iclass,iclass_capi,"_xxdata_11.xxdata_11() 2nd argument (iclass) can't be converted to int");
  if (f2py_success) {
  /* Processing variable isdimd */
    f2py_success = int_from_pyobj(&isdimd,isdimd_capi,"_xxdata_11.xxdata_11() 3rd argument (isdimd) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iddimd */
    f2py_success = int_from_pyobj(&iddimd,iddimd_capi,"_xxdata_11.xxdata_11() 4th argument (iddimd) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itdimd */
    f2py_success = int_from_pyobj(&itdimd,itdimd_capi,"_xxdata_11.xxdata_11() 5th argument (itdimd) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndptnl */
    f2py_success = int_from_pyobj(&ndptnl,ndptnl_capi,"_xxdata_11.xxdata_11() 6th argument (ndptnl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndptn */
    f2py_success = int_from_pyobj(&ndptn,ndptn_capi,"_xxdata_11.xxdata_11() 7th argument (ndptn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndptnc */
    f2py_success = int_from_pyobj(&ndptnc,ndptnc_capi,"_xxdata_11.xxdata_11() 8th argument (ndptnc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndcnct */
    f2py_success = int_from_pyobj(&ndcnct,ndcnct_capi,"_xxdata_11.xxdata_11() 9th argument (ndcnct) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iz0 */
  /* Processing variable is1min */
  /* Processing variable is1max */
  /* Processing variable nptnl */
  /* Processing variable ncnct */
  /* Processing variable iblmx */
  /* Processing variable ismax */
  /* Processing variable dnr_ele */
  slen(dnr_ele) = 12;
  f2py_success = string_from_pyobj(&dnr_ele,&slen(dnr_ele),"",dnr_ele_capi,"string_from_pyobj failed in converting hidden `dnr_ele' of _xxdata_11.xxdata_11 to C string");
  if (f2py_success) {
  /* Processing variable dnr_ams */
  /* Processing variable idmax */
  /* Processing variable itmax */
  /* Processing variable lres */
  /* Processing variable lstan */
  /* Processing variable lptn */
  /* Processing variable nptn */
  nptn_Dims[0]=ndptnl;
  capi_nptn_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_nptn_tmp = array_from_pyobj(NPY_INT,nptn_Dims,nptn_Rank,capi_nptn_intent,Py_None);
  if (capi_nptn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `nptn' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    nptn = (int *)(PyArray_DATA(capi_nptn_tmp));

  /* Processing variable nptnc */
  nptnc_Dims[0]=ndptnl,nptnc_Dims[1]=ndptn;
  capi_nptnc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_nptnc_tmp = array_from_pyobj(NPY_INT,nptnc_Dims,nptnc_Rank,capi_nptnc_intent,Py_None);
  if (capi_nptnc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `nptnc' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    nptnc = (int *)(PyArray_DATA(capi_nptnc_tmp));

  /* Processing variable iptnla */
  iptnla_Dims[0]=ndptnl;
  capi_iptnla_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iptnla_tmp = array_from_pyobj(NPY_INT,iptnla_Dims,iptnla_Rank,capi_iptnla_intent,Py_None);
  if (capi_iptnla_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `iptnla' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    iptnla = (int *)(PyArray_DATA(capi_iptnla_tmp));

  /* Processing variable iptna */
  iptna_Dims[0]=ndptnl,iptna_Dims[1]=ndptn;
  capi_iptna_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iptna_tmp = array_from_pyobj(NPY_INT,iptna_Dims,iptna_Rank,capi_iptna_intent,Py_None);
  if (capi_iptna_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `iptna' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    iptna = (int *)(PyArray_DATA(capi_iptna_tmp));

  /* Processing variable iptnca */
  iptnca_Dims[0]=ndptnl,iptnca_Dims[1]=ndptn,iptnca_Dims[2]=ndptnc;
  capi_iptnca_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iptnca_tmp = array_from_pyobj(NPY_INT,iptnca_Dims,iptnca_Rank,capi_iptnca_intent,Py_None);
  if (capi_iptnca_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `iptnca' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    iptnca = (int *)(PyArray_DATA(capi_iptnca_tmp));

  /* Processing variable icnctv */
  icnctv_Dims[0]=ndcnct;
  capi_icnctv_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_icnctv_tmp = array_from_pyobj(NPY_INT,icnctv_Dims,icnctv_Rank,capi_icnctv_intent,Py_None);
  if (capi_icnctv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `icnctv' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    icnctv = (int *)(PyArray_DATA(capi_icnctv_tmp));

  /* Processing variable isppr */
  isppr_Dims[0]=isdimd;
  capi_isppr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_isppr_tmp = array_from_pyobj(NPY_INT,isppr_Dims,isppr_Rank,capi_isppr_intent,Py_None);
  if (capi_isppr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `isppr' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    isppr = (int *)(PyArray_DATA(capi_isppr_tmp));

  /* Processing variable ispbr */
  ispbr_Dims[0]=isdimd;
  capi_ispbr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_ispbr_tmp = array_from_pyobj(NPY_INT,ispbr_Dims,ispbr_Rank,capi_ispbr_intent,Py_None);
  if (capi_ispbr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `ispbr' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    ispbr = (int *)(PyArray_DATA(capi_ispbr_tmp));

  /* Processing variable isstgr */
  isstgr_Dims[0]=isdimd;
  capi_isstgr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_isstgr_tmp = array_from_pyobj(NPY_INT,isstgr_Dims,isstgr_Rank,capi_isstgr_intent,Py_None);
  if (capi_isstgr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `isstgr' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    isstgr = (int *)(PyArray_DATA(capi_isstgr_tmp));

  /* Processing variable ddens */
  ddens_Dims[0]=iddimd;
  capi_ddens_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_ddens_tmp = array_from_pyobj(NPY_DOUBLE,ddens_Dims,ddens_Rank,capi_ddens_intent,Py_None);
  if (capi_ddens_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `ddens' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    ddens = (double *)(PyArray_DATA(capi_ddens_tmp));

  /* Processing variable dtev */
  dtev_Dims[0]=itdimd;
  capi_dtev_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_dtev_tmp = array_from_pyobj(NPY_DOUBLE,dtev_Dims,dtev_Rank,capi_dtev_intent,Py_None);
  if (capi_dtev_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `dtev' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    dtev = (double *)(PyArray_DATA(capi_dtev_tmp));

  /* Processing variable drcof */
  drcof_Dims[0]=isdimd,drcof_Dims[1]=itdimd,drcof_Dims[2]=iddimd;
  capi_drcof_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_drcof_tmp = array_from_pyobj(NPY_DOUBLE,drcof_Dims,drcof_Rank,capi_drcof_intent,Py_None);
  if (capi_drcof_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_11_error,"failed in converting hidden `drcof' of _xxdata_11.xxdata_11 to C/Fortran array" );
  } else {
    drcof = (double *)(PyArray_DATA(capi_drcof_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iunit,&iclass,&isdimd,&iddimd,&itdimd,&ndptnl,&ndptn,&ndptnc,&ndcnct,&iz0,&is1min,&is1max,&nptnl,nptn,nptnc,iptnla,iptna,iptnca,&ncnct,icnctv,&iblmx,&ismax,dnr_ele,&dnr_ams,isppr,ispbr,isstgr,&idmax,&itmax,ddens,dtev,drcof,&lres,&lstan,&lptn,slen(dnr_ele));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("iiiiNNNNNiNiiydNNNiiNNNiii",iz0,is1min,is1max,nptnl,capi_nptn_tmp,capi_nptnc_tmp,capi_iptnla_tmp,capi_iptna_tmp,capi_iptnca_tmp,ncnct,capi_icnctv_tmp,iblmx,ismax,dnr_ele,dnr_ams,capi_isppr_tmp,capi_ispbr_tmp,capi_isstgr_tmp,idmax,itmax,capi_ddens_tmp,capi_dtev_tmp,capi_drcof_tmp,lres,lstan,lptn);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_drcof_tmp == NULL) ... else of drcof*/
  /* End of cleaning variable drcof */
  }  /*if (capi_dtev_tmp == NULL) ... else of dtev*/
  /* End of cleaning variable dtev */
  }  /*if (capi_ddens_tmp == NULL) ... else of ddens*/
  /* End of cleaning variable ddens */
  }  /*if (capi_isstgr_tmp == NULL) ... else of isstgr*/
  /* End of cleaning variable isstgr */
  }  /*if (capi_ispbr_tmp == NULL) ... else of ispbr*/
  /* End of cleaning variable ispbr */
  }  /*if (capi_isppr_tmp == NULL) ... else of isppr*/
  /* End of cleaning variable isppr */
  }  /*if (capi_icnctv_tmp == NULL) ... else of icnctv*/
  /* End of cleaning variable icnctv */
  }  /*if (capi_iptnca_tmp == NULL) ... else of iptnca*/
  /* End of cleaning variable iptnca */
  }  /*if (capi_iptna_tmp == NULL) ... else of iptna*/
  /* End of cleaning variable iptna */
  }  /*if (capi_iptnla_tmp == NULL) ... else of iptnla*/
  /* End of cleaning variable iptnla */
  }  /*if (capi_nptnc_tmp == NULL) ... else of nptnc*/
  /* End of cleaning variable nptnc */
  }  /*if (capi_nptn_tmp == NULL) ... else of nptn*/
  /* End of cleaning variable nptn */
  /* End of cleaning variable lptn */
  /* End of cleaning variable lstan */
  /* End of cleaning variable lres */
  /* End of cleaning variable itmax */
  /* End of cleaning variable idmax */
  /* End of cleaning variable dnr_ams */
    STRINGFREE(dnr_ele);
  }  /*if (f2py_success) of dnr_ele*/
  /* End of cleaning variable dnr_ele */
  /* End of cleaning variable ismax */
  /* End of cleaning variable iblmx */
  /* End of cleaning variable ncnct */
  /* End of cleaning variable nptnl */
  /* End of cleaning variable is1max */
  /* End of cleaning variable is1min */
  /* End of cleaning variable iz0 */
  } /*if (f2py_success) of ndcnct*/
  /* End of cleaning variable ndcnct */
  } /*if (f2py_success) of ndptnc*/
  /* End of cleaning variable ndptnc */
  } /*if (f2py_success) of ndptn*/
  /* End of cleaning variable ndptn */
  } /*if (f2py_success) of ndptnl*/
  /* End of cleaning variable ndptnl */
  } /*if (f2py_success) of itdimd*/
  /* End of cleaning variable itdimd */
  } /*if (f2py_success) of iddimd*/
  /* End of cleaning variable iddimd */
  } /*if (f2py_success) of isdimd*/
  /* End of cleaning variable isdimd */
  } /*if (f2py_success) of iclass*/
  /* End of cleaning variable iclass */
  } /*if (f2py_success) of iunit*/
  /* End of cleaning variable iunit */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of xxdata_11 ******************************/

/****************************** helper_open_file ******************************/
static char doc_f2py_rout__xxdata_11_helper_open_file[] = "\
iunit = helper_open_file(filename)\n\nWrapper for ``helper_open_file``.\
\n\nParameters\n----------\n"
"filename : input string(len=120)\n"
"\nReturns\n-------\n"
"iunit : int";
/* extern void F_FUNC_US(helper_open_file,HELPER_OPEN_FILE)(int*,string,size_t); */
static PyObject *f2py_rout__xxdata_11_helper_open_file(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iunit = 0;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  static char *capi_kwlist[] = {"filename",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:_xxdata_11.helper_open_file",\
    capi_kwlist,&filename_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable filename */
  slen(filename) = 120;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 1st argument `filename' of _xxdata_11.helper_open_file to C string");
  if (f2py_success) {
  /* Processing variable iunit */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iunit,filename,slen(filename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",iunit);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable iunit */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of helper_open_file **************************/

/***************************** helper_close_file *****************************/
static char doc_f2py_rout__xxdata_11_helper_close_file[] = "\
helper_close_file(iunit)\n\nWrapper for ``helper_close_file``.\
\n\nParameters\n----------\n"
"iunit : input int";
/* extern void F_FUNC_US(helper_close_file,HELPER_CLOSE_FILE)(int*); */
static PyObject *f2py_rout__xxdata_11_helper_close_file(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iunit = 0;
  PyObject *iunit_capi = Py_None;
  static char *capi_kwlist[] = {"iunit",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:_xxdata_11.helper_close_file",\
    capi_kwlist,&iunit_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iunit */
    f2py_success = int_from_pyobj(&iunit,iunit_capi,"_xxdata_11.helper_close_file() 1st argument (iunit) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iunit);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of iunit*/
  /* End of cleaning variable iunit */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of helper_close_file **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"xxdata_11",-1,{{-1}},0,(char *)F_FUNC_US(xxdata_11,XXDATA_11),(f2py_init_func)f2py_rout__xxdata_11_xxdata_11,doc_f2py_rout__xxdata_11_xxdata_11},
  {"helper_open_file",-1,{{-1}},0,(char *)F_FUNC_US(helper_open_file,HELPER_OPEN_FILE),(f2py_init_func)f2py_rout__xxdata_11_helper_open_file,doc_f2py_rout__xxdata_11_helper_open_file},
  {"helper_close_file",-1,{{-1}},0,(char *)F_FUNC_US(helper_close_file,HELPER_CLOSE_FILE),(f2py_init_func)f2py_rout__xxdata_11_helper_close_file,doc_f2py_rout__xxdata_11_helper_close_file},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_xxdata_11",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__xxdata_11(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_xxdata_11(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _xxdata_11_module = PyModule_Create(&moduledef);
#else
  m = _xxdata_11_module = Py_InitModule("_xxdata_11", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _xxdata_11 (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_xxdata_11' is auto-generated with f2py (version:2).\nFunctions:\n"
"  iz0,is1min,is1max,nptnl,nptn,nptnc,iptnla,iptna,iptnca,ncnct,icnctv,iblmx,ismax,dnr_ele,dnr_ams,isppr,ispbr,isstgr,idmax,itmax,ddens,dtev,drcof,lres,lstan,lptn = xxdata_11(iunit,iclass,isdimd,iddimd,itdimd,ndptnl,ndptn,ndptnc,ndcnct)\n"
"  iunit = helper_open_file(filename)\n"
"  helper_close_file(iunit)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _xxdata_11_error = PyErr_NewException ("_xxdata_11.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_xxdata_11");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
