/* File: _xxdata_15module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Jul 13 19:31:56 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_xxdata_15_error;
static PyObject *_xxdata_15_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _xxdata_15_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _xxdata_15_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(xxdata_15,XXDATA_15)(int*,string,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,string,int*,int*,int*,int*,int*,int*,int*,int*,int*,string*,int*,int*,int*,int*,int*,int*,string*,string*,string*,string*,double*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,int*,string*,size_t,size_t);
extern void F_FUNC_US(helper_open_file,HELPER_OPEN_FILE)(int*,string,size_t);
extern void F_FUNC_US(helper_close_file,HELPER_CLOSE_FILE)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* xxdata_15 *********************************/
static char doc_f2py_rout__xxdata_15_xxdata_15[] = "\
iz0,is,is1,esym,nptnl,nptn,nptnc,iptnla,iptna,iptnca,ncnct,icnctv,ncptn_stack,cptn_stack,lres,lptn,lcmt,lsup,nbsel,isela,cwavel,cfile,ctype,cindm,wavel,ispbr,isppr,isstgr,iszr,ita,ida,teta,teda,pec,pec_max,ncmt_stack,cmt_stack = xxdata_15(iunit,dsname,nstore,ntdim,nddim,ndptnl,ndptn,ndptnc,ndcnct,ndstack,ndcmt)\n\nWrapper for ``xxdata_15``.\
\n\nParameters\n----------\n"
"iunit : input int\n"
"dsname : input string(len=80)\n"
"nstore : input int\n"
"ntdim : input int\n"
"nddim : input int\n"
"ndptnl : input int\n"
"ndptn : input int\n"
"ndptnc : input int\n"
"ndcnct : input int\n"
"ndstack : input int\n"
"ndcmt : input int\n"
"\nReturns\n-------\n"
"iz0 : int\n"
"is : int\n"
"is1 : int\n"
"esym : string(len=2)\n"
"nptnl : int\n"
"nptn : rank-1 array('i') with bounds (ndptnl)\n"
"nptnc : rank-2 array('i') with bounds (ndptnl,ndptn)\n"
"iptnla : rank-1 array('i') with bounds (ndptnl)\n"
"iptna : rank-2 array('i') with bounds (ndptnl,ndptn)\n"
"iptnca : rank-3 array('i') with bounds (ndptnl,ndptn,ndptnc)\n"
"ncnct : int\n"
"icnctv : rank-1 array('i') with bounds (ndcnct)\n"
"ncptn_stack : int\n"
"cptn_stack : rank-2 array('S') with bounds (ndstack,80)\n"
"lres : int\n"
"lptn : int\n"
"lcmt : int\n"
"lsup : int\n"
"nbsel : int\n"
"isela : rank-1 array('i') with bounds (nstore)\n"
"cwavel : rank-2 array('S') with bounds (nstore,10)\n"
"cfile : rank-2 array('S') with bounds (nstore,8)\n"
"ctype : rank-2 array('S') with bounds (nstore,8)\n"
"cindm : rank-2 array('S') with bounds (nstore,2)\n"
"wavel : rank-1 array('d') with bounds (nstore)\n"
"ispbr : rank-1 array('i') with bounds (nstore)\n"
"isppr : rank-1 array('i') with bounds (nstore)\n"
"isstgr : rank-1 array('i') with bounds (nstore)\n"
"iszr : rank-1 array('i') with bounds (nstore)\n"
"ita : rank-1 array('i') with bounds (nstore)\n"
"ida : rank-1 array('i') with bounds (nstore)\n"
"teta : rank-2 array('d') with bounds (ntdim,nstore)\n"
"teda : rank-2 array('d') with bounds (nddim,nstore)\n"
"pec : rank-3 array('d') with bounds (ntdim,nddim,nstore)\n"
"pec_max : rank-1 array('d') with bounds (nstore)\n"
"ncmt_stack : int\n"
"cmt_stack : rank-2 array('S') with bounds (ndcmt,80)";
/* extern void F_FUNC_US(xxdata_15,XXDATA_15)(int*,string,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,string,int*,int*,int*,int*,int*,int*,int*,int*,int*,string*,int*,int*,int*,int*,int*,int*,string*,string*,string*,string*,double*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,int*,string*,size_t,size_t); */
static PyObject *f2py_rout__xxdata_15_xxdata_15(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,string,int*,int*,int*,int*,int*,int*,int*,int*,int*,string*,int*,int*,int*,int*,int*,int*,string*,string*,string*,string*,double*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,int*,string*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iunit = 0;
  PyObject *iunit_capi = Py_None;
  string dsname = NULL;
  int slen(dsname);
  PyObject *dsname_capi = Py_None;
  int nstore = 0;
  PyObject *nstore_capi = Py_None;
  int ntdim = 0;
  PyObject *ntdim_capi = Py_None;
  int nddim = 0;
  PyObject *nddim_capi = Py_None;
  int ndptnl = 0;
  PyObject *ndptnl_capi = Py_None;
  int ndptn = 0;
  PyObject *ndptn_capi = Py_None;
  int ndptnc = 0;
  PyObject *ndptnc_capi = Py_None;
  int ndcnct = 0;
  PyObject *ndcnct_capi = Py_None;
  int ndstack = 0;
  PyObject *ndstack_capi = Py_None;
  int ndcmt = 0;
  PyObject *ndcmt_capi = Py_None;
  int iz0 = 0;
  int is = 0;
  int is1 = 0;
  string esym = NULL;
  int slen(esym);
  PyObject *esym_capi = Py_None;
  int nptnl = 0;
  int *nptn = NULL;
  npy_intp nptn_Dims[1] = {-1};
  const int nptn_Rank = 1;
  PyArrayObject *capi_nptn_tmp = NULL;
  int capi_nptn_intent = 0;
  int *nptnc = NULL;
  npy_intp nptnc_Dims[2] = {-1, -1};
  const int nptnc_Rank = 2;
  PyArrayObject *capi_nptnc_tmp = NULL;
  int capi_nptnc_intent = 0;
  int *iptnla = NULL;
  npy_intp iptnla_Dims[1] = {-1};
  const int iptnla_Rank = 1;
  PyArrayObject *capi_iptnla_tmp = NULL;
  int capi_iptnla_intent = 0;
  int *iptna = NULL;
  npy_intp iptna_Dims[2] = {-1, -1};
  const int iptna_Rank = 2;
  PyArrayObject *capi_iptna_tmp = NULL;
  int capi_iptna_intent = 0;
  int *iptnca = NULL;
  npy_intp iptnca_Dims[3] = {-1, -1, -1};
  const int iptnca_Rank = 3;
  PyArrayObject *capi_iptnca_tmp = NULL;
  int capi_iptnca_intent = 0;
  int ncnct = 0;
  int *icnctv = NULL;
  npy_intp icnctv_Dims[1] = {-1};
  const int icnctv_Rank = 1;
  PyArrayObject *capi_icnctv_tmp = NULL;
  int capi_icnctv_intent = 0;
  int ncptn_stack = 0;
  string *cptn_stack = NULL;
  npy_intp cptn_stack_Dims[2] = {-1, -1};
  const int cptn_stack_Rank = 2;
  PyArrayObject *capi_cptn_stack_tmp = NULL;
  int capi_cptn_stack_intent = 0;
  int lres = 0;
  int lptn = 0;
  int lcmt = 0;
  int lsup = 0;
  int nbsel = 0;
  int *isela = NULL;
  npy_intp isela_Dims[1] = {-1};
  const int isela_Rank = 1;
  PyArrayObject *capi_isela_tmp = NULL;
  int capi_isela_intent = 0;
  string *cwavel = NULL;
  npy_intp cwavel_Dims[2] = {-1, -1};
  const int cwavel_Rank = 2;
  PyArrayObject *capi_cwavel_tmp = NULL;
  int capi_cwavel_intent = 0;
  string *cfile = NULL;
  npy_intp cfile_Dims[2] = {-1, -1};
  const int cfile_Rank = 2;
  PyArrayObject *capi_cfile_tmp = NULL;
  int capi_cfile_intent = 0;
  string *ctype = NULL;
  npy_intp ctype_Dims[2] = {-1, -1};
  const int ctype_Rank = 2;
  PyArrayObject *capi_ctype_tmp = NULL;
  int capi_ctype_intent = 0;
  string *cindm = NULL;
  npy_intp cindm_Dims[2] = {-1, -1};
  const int cindm_Rank = 2;
  PyArrayObject *capi_cindm_tmp = NULL;
  int capi_cindm_intent = 0;
  double *wavel = NULL;
  npy_intp wavel_Dims[1] = {-1};
  const int wavel_Rank = 1;
  PyArrayObject *capi_wavel_tmp = NULL;
  int capi_wavel_intent = 0;
  int *ispbr = NULL;
  npy_intp ispbr_Dims[1] = {-1};
  const int ispbr_Rank = 1;
  PyArrayObject *capi_ispbr_tmp = NULL;
  int capi_ispbr_intent = 0;
  int *isppr = NULL;
  npy_intp isppr_Dims[1] = {-1};
  const int isppr_Rank = 1;
  PyArrayObject *capi_isppr_tmp = NULL;
  int capi_isppr_intent = 0;
  int *isstgr = NULL;
  npy_intp isstgr_Dims[1] = {-1};
  const int isstgr_Rank = 1;
  PyArrayObject *capi_isstgr_tmp = NULL;
  int capi_isstgr_intent = 0;
  int *iszr = NULL;
  npy_intp iszr_Dims[1] = {-1};
  const int iszr_Rank = 1;
  PyArrayObject *capi_iszr_tmp = NULL;
  int capi_iszr_intent = 0;
  int *ita = NULL;
  npy_intp ita_Dims[1] = {-1};
  const int ita_Rank = 1;
  PyArrayObject *capi_ita_tmp = NULL;
  int capi_ita_intent = 0;
  int *ida = NULL;
  npy_intp ida_Dims[1] = {-1};
  const int ida_Rank = 1;
  PyArrayObject *capi_ida_tmp = NULL;
  int capi_ida_intent = 0;
  double *teta = NULL;
  npy_intp teta_Dims[2] = {-1, -1};
  const int teta_Rank = 2;
  PyArrayObject *capi_teta_tmp = NULL;
  int capi_teta_intent = 0;
  double *teda = NULL;
  npy_intp teda_Dims[2] = {-1, -1};
  const int teda_Rank = 2;
  PyArrayObject *capi_teda_tmp = NULL;
  int capi_teda_intent = 0;
  double *pec = NULL;
  npy_intp pec_Dims[3] = {-1, -1, -1};
  const int pec_Rank = 3;
  PyArrayObject *capi_pec_tmp = NULL;
  int capi_pec_intent = 0;
  double *pec_max = NULL;
  npy_intp pec_max_Dims[1] = {-1};
  const int pec_max_Rank = 1;
  PyArrayObject *capi_pec_max_tmp = NULL;
  int capi_pec_max_intent = 0;
  int ncmt_stack = 0;
  string *cmt_stack = NULL;
  npy_intp cmt_stack_Dims[2] = {-1, -1};
  const int cmt_stack_Rank = 2;
  PyArrayObject *capi_cmt_stack_tmp = NULL;
  int capi_cmt_stack_intent = 0;
  static char *capi_kwlist[] = {"iunit","dsname","nstore","ntdim","nddim","ndptnl","ndptn","ndptnc","ndcnct","ndstack","ndcmt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO:_xxdata_15.xxdata_15",\
    capi_kwlist,&iunit_capi,&dsname_capi,&nstore_capi,&ntdim_capi,&nddim_capi,&ndptnl_capi,&ndptn_capi,&ndptnc_capi,&ndcnct_capi,&ndstack_capi,&ndcmt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iunit */
    f2py_success = int_from_pyobj(&iunit,iunit_capi,"_xxdata_15.xxdata_15() 1st argument (iunit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dsname */
  slen(dsname) = 80;
  f2py_success = string_from_pyobj(&dsname,&slen(dsname),"",dsname_capi,"string_from_pyobj failed in converting 2nd argument `dsname' of _xxdata_15.xxdata_15 to C string");
  if (f2py_success) {
  /* Processing variable nstore */
    f2py_success = int_from_pyobj(&nstore,nstore_capi,"_xxdata_15.xxdata_15() 3rd argument (nstore) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ntdim */
    f2py_success = int_from_pyobj(&ntdim,ntdim_capi,"_xxdata_15.xxdata_15() 4th argument (ntdim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nddim */
    f2py_success = int_from_pyobj(&nddim,nddim_capi,"_xxdata_15.xxdata_15() 5th argument (nddim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndptnl */
    f2py_success = int_from_pyobj(&ndptnl,ndptnl_capi,"_xxdata_15.xxdata_15() 6th argument (ndptnl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndptn */
    f2py_success = int_from_pyobj(&ndptn,ndptn_capi,"_xxdata_15.xxdata_15() 7th argument (ndptn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndptnc */
    f2py_success = int_from_pyobj(&ndptnc,ndptnc_capi,"_xxdata_15.xxdata_15() 8th argument (ndptnc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndcnct */
    f2py_success = int_from_pyobj(&ndcnct,ndcnct_capi,"_xxdata_15.xxdata_15() 9th argument (ndcnct) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndstack */
    f2py_success = int_from_pyobj(&ndstack,ndstack_capi,"_xxdata_15.xxdata_15() 10th argument (ndstack) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndcmt */
    f2py_success = int_from_pyobj(&ndcmt,ndcmt_capi,"_xxdata_15.xxdata_15() 11st argument (ndcmt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iz0 */
  /* Processing variable is */
  /* Processing variable is1 */
  /* Processing variable esym */
  slen(esym) = 2;
  f2py_success = string_from_pyobj(&esym,&slen(esym),"",esym_capi,"string_from_pyobj failed in converting hidden `esym' of _xxdata_15.xxdata_15 to C string");
  if (f2py_success) {
  /* Processing variable nptnl */
  /* Processing variable ncnct */
  /* Processing variable ncptn_stack */
  /* Processing variable lres */
  /* Processing variable lptn */
  /* Processing variable lcmt */
  /* Processing variable lsup */
  /* Processing variable nbsel */
  /* Processing variable ncmt_stack */
  /* Processing variable nptn */
  nptn_Dims[0]=ndptnl;
  capi_nptn_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_nptn_tmp = array_from_pyobj(NPY_INT,nptn_Dims,nptn_Rank,capi_nptn_intent,Py_None);
  if (capi_nptn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `nptn' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    nptn = (int *)(PyArray_DATA(capi_nptn_tmp));

  /* Processing variable nptnc */
  nptnc_Dims[0]=ndptnl,nptnc_Dims[1]=ndptn;
  capi_nptnc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_nptnc_tmp = array_from_pyobj(NPY_INT,nptnc_Dims,nptnc_Rank,capi_nptnc_intent,Py_None);
  if (capi_nptnc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `nptnc' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    nptnc = (int *)(PyArray_DATA(capi_nptnc_tmp));

  /* Processing variable iptnla */
  iptnla_Dims[0]=ndptnl;
  capi_iptnla_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iptnla_tmp = array_from_pyobj(NPY_INT,iptnla_Dims,iptnla_Rank,capi_iptnla_intent,Py_None);
  if (capi_iptnla_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `iptnla' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    iptnla = (int *)(PyArray_DATA(capi_iptnla_tmp));

  /* Processing variable iptna */
  iptna_Dims[0]=ndptnl,iptna_Dims[1]=ndptn;
  capi_iptna_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iptna_tmp = array_from_pyobj(NPY_INT,iptna_Dims,iptna_Rank,capi_iptna_intent,Py_None);
  if (capi_iptna_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `iptna' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    iptna = (int *)(PyArray_DATA(capi_iptna_tmp));

  /* Processing variable iptnca */
  iptnca_Dims[0]=ndptnl,iptnca_Dims[1]=ndptn,iptnca_Dims[2]=ndptnc;
  capi_iptnca_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iptnca_tmp = array_from_pyobj(NPY_INT,iptnca_Dims,iptnca_Rank,capi_iptnca_intent,Py_None);
  if (capi_iptnca_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `iptnca' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    iptnca = (int *)(PyArray_DATA(capi_iptnca_tmp));

  /* Processing variable icnctv */
  icnctv_Dims[0]=ndcnct;
  capi_icnctv_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_icnctv_tmp = array_from_pyobj(NPY_INT,icnctv_Dims,icnctv_Rank,capi_icnctv_intent,Py_None);
  if (capi_icnctv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `icnctv' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    icnctv = (int *)(PyArray_DATA(capi_icnctv_tmp));

  /* Processing variable cptn_stack */
  cptn_stack_Dims[0]=ndstack,cptn_stack_Dims[1]=80;
  capi_cptn_stack_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_cptn_stack_tmp = array_from_pyobj(NPY_CHAR,cptn_stack_Dims,cptn_stack_Rank,capi_cptn_stack_intent,Py_None);
  if (capi_cptn_stack_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `cptn_stack' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    cptn_stack = (string *)(PyArray_DATA(capi_cptn_stack_tmp));

  /* Processing variable isela */
  isela_Dims[0]=nstore;
  capi_isela_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_isela_tmp = array_from_pyobj(NPY_INT,isela_Dims,isela_Rank,capi_isela_intent,Py_None);
  if (capi_isela_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `isela' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    isela = (int *)(PyArray_DATA(capi_isela_tmp));

  /* Processing variable cwavel */
  cwavel_Dims[0]=nstore,cwavel_Dims[1]=10;
  capi_cwavel_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_cwavel_tmp = array_from_pyobj(NPY_CHAR,cwavel_Dims,cwavel_Rank,capi_cwavel_intent,Py_None);
  if (capi_cwavel_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `cwavel' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    cwavel = (string *)(PyArray_DATA(capi_cwavel_tmp));

  /* Processing variable cfile */
  cfile_Dims[0]=nstore,cfile_Dims[1]=8;
  capi_cfile_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_cfile_tmp = array_from_pyobj(NPY_CHAR,cfile_Dims,cfile_Rank,capi_cfile_intent,Py_None);
  if (capi_cfile_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `cfile' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    cfile = (string *)(PyArray_DATA(capi_cfile_tmp));

  /* Processing variable ctype */
  ctype_Dims[0]=nstore,ctype_Dims[1]=8;
  capi_ctype_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_ctype_tmp = array_from_pyobj(NPY_CHAR,ctype_Dims,ctype_Rank,capi_ctype_intent,Py_None);
  if (capi_ctype_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `ctype' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    ctype = (string *)(PyArray_DATA(capi_ctype_tmp));

  /* Processing variable cindm */
  cindm_Dims[0]=nstore,cindm_Dims[1]=2;
  capi_cindm_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_cindm_tmp = array_from_pyobj(NPY_CHAR,cindm_Dims,cindm_Rank,capi_cindm_intent,Py_None);
  if (capi_cindm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `cindm' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    cindm = (string *)(PyArray_DATA(capi_cindm_tmp));

  /* Processing variable wavel */
  wavel_Dims[0]=nstore;
  capi_wavel_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_wavel_tmp = array_from_pyobj(NPY_DOUBLE,wavel_Dims,wavel_Rank,capi_wavel_intent,Py_None);
  if (capi_wavel_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `wavel' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    wavel = (double *)(PyArray_DATA(capi_wavel_tmp));

  /* Processing variable ispbr */
  ispbr_Dims[0]=nstore;
  capi_ispbr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_ispbr_tmp = array_from_pyobj(NPY_INT,ispbr_Dims,ispbr_Rank,capi_ispbr_intent,Py_None);
  if (capi_ispbr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `ispbr' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    ispbr = (int *)(PyArray_DATA(capi_ispbr_tmp));

  /* Processing variable isppr */
  isppr_Dims[0]=nstore;
  capi_isppr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_isppr_tmp = array_from_pyobj(NPY_INT,isppr_Dims,isppr_Rank,capi_isppr_intent,Py_None);
  if (capi_isppr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `isppr' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    isppr = (int *)(PyArray_DATA(capi_isppr_tmp));

  /* Processing variable isstgr */
  isstgr_Dims[0]=nstore;
  capi_isstgr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_isstgr_tmp = array_from_pyobj(NPY_INT,isstgr_Dims,isstgr_Rank,capi_isstgr_intent,Py_None);
  if (capi_isstgr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `isstgr' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    isstgr = (int *)(PyArray_DATA(capi_isstgr_tmp));

  /* Processing variable iszr */
  iszr_Dims[0]=nstore;
  capi_iszr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iszr_tmp = array_from_pyobj(NPY_INT,iszr_Dims,iszr_Rank,capi_iszr_intent,Py_None);
  if (capi_iszr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `iszr' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    iszr = (int *)(PyArray_DATA(capi_iszr_tmp));

  /* Processing variable ita */
  ita_Dims[0]=nstore;
  capi_ita_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_ita_tmp = array_from_pyobj(NPY_INT,ita_Dims,ita_Rank,capi_ita_intent,Py_None);
  if (capi_ita_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `ita' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    ita = (int *)(PyArray_DATA(capi_ita_tmp));

  /* Processing variable ida */
  ida_Dims[0]=nstore;
  capi_ida_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_ida_tmp = array_from_pyobj(NPY_INT,ida_Dims,ida_Rank,capi_ida_intent,Py_None);
  if (capi_ida_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `ida' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    ida = (int *)(PyArray_DATA(capi_ida_tmp));

  /* Processing variable teta */
  teta_Dims[0]=ntdim,teta_Dims[1]=nstore;
  capi_teta_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_teta_tmp = array_from_pyobj(NPY_DOUBLE,teta_Dims,teta_Rank,capi_teta_intent,Py_None);
  if (capi_teta_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `teta' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    teta = (double *)(PyArray_DATA(capi_teta_tmp));

  /* Processing variable teda */
  teda_Dims[0]=nddim,teda_Dims[1]=nstore;
  capi_teda_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_teda_tmp = array_from_pyobj(NPY_DOUBLE,teda_Dims,teda_Rank,capi_teda_intent,Py_None);
  if (capi_teda_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `teda' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    teda = (double *)(PyArray_DATA(capi_teda_tmp));

  /* Processing variable pec */
  pec_Dims[0]=ntdim,pec_Dims[1]=nddim,pec_Dims[2]=nstore;
  capi_pec_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_pec_tmp = array_from_pyobj(NPY_DOUBLE,pec_Dims,pec_Rank,capi_pec_intent,Py_None);
  if (capi_pec_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `pec' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    pec = (double *)(PyArray_DATA(capi_pec_tmp));

  /* Processing variable pec_max */
  pec_max_Dims[0]=nstore;
  capi_pec_max_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_pec_max_tmp = array_from_pyobj(NPY_DOUBLE,pec_max_Dims,pec_max_Rank,capi_pec_max_intent,Py_None);
  if (capi_pec_max_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `pec_max' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    pec_max = (double *)(PyArray_DATA(capi_pec_max_tmp));

  /* Processing variable cmt_stack */
  cmt_stack_Dims[0]=ndcmt,cmt_stack_Dims[1]=80;
  capi_cmt_stack_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_cmt_stack_tmp = array_from_pyobj(NPY_CHAR,cmt_stack_Dims,cmt_stack_Rank,capi_cmt_stack_intent,Py_None);
  if (capi_cmt_stack_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_xxdata_15_error,"failed in converting hidden `cmt_stack' of _xxdata_15.xxdata_15 to C/Fortran array" );
  } else {
    cmt_stack = (string *)(PyArray_DATA(capi_cmt_stack_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iunit,dsname,&nstore,&ntdim,&nddim,&ndptnl,&ndptn,&ndptnc,&ndcnct,&ndstack,&ndcmt,&iz0,&is,&is1,esym,&nptnl,nptn,nptnc,iptnla,iptna,iptnca,&ncnct,icnctv,&ncptn_stack,cptn_stack,&lres,&lptn,&lcmt,&lsup,&nbsel,isela,cwavel,cfile,ctype,cindm,wavel,ispbr,isppr,isstgr,iszr,ita,ida,teta,teda,pec,pec_max,&ncmt_stack,cmt_stack,slen(dsname),slen(esym));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("iiiyiNNNNNiNiNiiiiiNNNNNNNNNNNNNNNNiN",iz0,is,is1,esym,nptnl,capi_nptn_tmp,capi_nptnc_tmp,capi_iptnla_tmp,capi_iptna_tmp,capi_iptnca_tmp,ncnct,capi_icnctv_tmp,ncptn_stack,capi_cptn_stack_tmp,lres,lptn,lcmt,lsup,nbsel,capi_isela_tmp,capi_cwavel_tmp,capi_cfile_tmp,capi_ctype_tmp,capi_cindm_tmp,capi_wavel_tmp,capi_ispbr_tmp,capi_isppr_tmp,capi_isstgr_tmp,capi_iszr_tmp,capi_ita_tmp,capi_ida_tmp,capi_teta_tmp,capi_teda_tmp,capi_pec_tmp,capi_pec_max_tmp,ncmt_stack,capi_cmt_stack_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_cmt_stack_tmp == NULL) ... else of cmt_stack*/
  /* End of cleaning variable cmt_stack */
  }  /*if (capi_pec_max_tmp == NULL) ... else of pec_max*/
  /* End of cleaning variable pec_max */
  }  /*if (capi_pec_tmp == NULL) ... else of pec*/
  /* End of cleaning variable pec */
  }  /*if (capi_teda_tmp == NULL) ... else of teda*/
  /* End of cleaning variable teda */
  }  /*if (capi_teta_tmp == NULL) ... else of teta*/
  /* End of cleaning variable teta */
  }  /*if (capi_ida_tmp == NULL) ... else of ida*/
  /* End of cleaning variable ida */
  }  /*if (capi_ita_tmp == NULL) ... else of ita*/
  /* End of cleaning variable ita */
  }  /*if (capi_iszr_tmp == NULL) ... else of iszr*/
  /* End of cleaning variable iszr */
  }  /*if (capi_isstgr_tmp == NULL) ... else of isstgr*/
  /* End of cleaning variable isstgr */
  }  /*if (capi_isppr_tmp == NULL) ... else of isppr*/
  /* End of cleaning variable isppr */
  }  /*if (capi_ispbr_tmp == NULL) ... else of ispbr*/
  /* End of cleaning variable ispbr */
  }  /*if (capi_wavel_tmp == NULL) ... else of wavel*/
  /* End of cleaning variable wavel */
  }  /*if (capi_cindm_tmp == NULL) ... else of cindm*/
  /* End of cleaning variable cindm */
  }  /*if (capi_ctype_tmp == NULL) ... else of ctype*/
  /* End of cleaning variable ctype */
  }  /*if (capi_cfile_tmp == NULL) ... else of cfile*/
  /* End of cleaning variable cfile */
  }  /*if (capi_cwavel_tmp == NULL) ... else of cwavel*/
  /* End of cleaning variable cwavel */
  }  /*if (capi_isela_tmp == NULL) ... else of isela*/
  /* End of cleaning variable isela */
  }  /*if (capi_cptn_stack_tmp == NULL) ... else of cptn_stack*/
  /* End of cleaning variable cptn_stack */
  }  /*if (capi_icnctv_tmp == NULL) ... else of icnctv*/
  /* End of cleaning variable icnctv */
  }  /*if (capi_iptnca_tmp == NULL) ... else of iptnca*/
  /* End of cleaning variable iptnca */
  }  /*if (capi_iptna_tmp == NULL) ... else of iptna*/
  /* End of cleaning variable iptna */
  }  /*if (capi_iptnla_tmp == NULL) ... else of iptnla*/
  /* End of cleaning variable iptnla */
  }  /*if (capi_nptnc_tmp == NULL) ... else of nptnc*/
  /* End of cleaning variable nptnc */
  }  /*if (capi_nptn_tmp == NULL) ... else of nptn*/
  /* End of cleaning variable nptn */
  /* End of cleaning variable ncmt_stack */
  /* End of cleaning variable nbsel */
  /* End of cleaning variable lsup */
  /* End of cleaning variable lcmt */
  /* End of cleaning variable lptn */
  /* End of cleaning variable lres */
  /* End of cleaning variable ncptn_stack */
  /* End of cleaning variable ncnct */
  /* End of cleaning variable nptnl */
    STRINGFREE(esym);
  }  /*if (f2py_success) of esym*/
  /* End of cleaning variable esym */
  /* End of cleaning variable is1 */
  /* End of cleaning variable is */
  /* End of cleaning variable iz0 */
  } /*if (f2py_success) of ndcmt*/
  /* End of cleaning variable ndcmt */
  } /*if (f2py_success) of ndstack*/
  /* End of cleaning variable ndstack */
  } /*if (f2py_success) of ndcnct*/
  /* End of cleaning variable ndcnct */
  } /*if (f2py_success) of ndptnc*/
  /* End of cleaning variable ndptnc */
  } /*if (f2py_success) of ndptn*/
  /* End of cleaning variable ndptn */
  } /*if (f2py_success) of ndptnl*/
  /* End of cleaning variable ndptnl */
  } /*if (f2py_success) of nddim*/
  /* End of cleaning variable nddim */
  } /*if (f2py_success) of ntdim*/
  /* End of cleaning variable ntdim */
  } /*if (f2py_success) of nstore*/
  /* End of cleaning variable nstore */
    STRINGFREE(dsname);
  }  /*if (f2py_success) of dsname*/
  /* End of cleaning variable dsname */
  } /*if (f2py_success) of iunit*/
  /* End of cleaning variable iunit */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of xxdata_15 ******************************/

/****************************** helper_open_file ******************************/
static char doc_f2py_rout__xxdata_15_helper_open_file[] = "\
iunit = helper_open_file(filename)\n\nWrapper for ``helper_open_file``.\
\n\nParameters\n----------\n"
"filename : input string(len=120)\n"
"\nReturns\n-------\n"
"iunit : int";
/* extern void F_FUNC_US(helper_open_file,HELPER_OPEN_FILE)(int*,string,size_t); */
static PyObject *f2py_rout__xxdata_15_helper_open_file(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iunit = 0;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  static char *capi_kwlist[] = {"filename",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:_xxdata_15.helper_open_file",\
    capi_kwlist,&filename_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable filename */
  slen(filename) = 120;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 1st argument `filename' of _xxdata_15.helper_open_file to C string");
  if (f2py_success) {
  /* Processing variable iunit */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iunit,filename,slen(filename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",iunit);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable iunit */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of helper_open_file **************************/

/***************************** helper_close_file *****************************/
static char doc_f2py_rout__xxdata_15_helper_close_file[] = "\
helper_close_file(iunit)\n\nWrapper for ``helper_close_file``.\
\n\nParameters\n----------\n"
"iunit : input int";
/* extern void F_FUNC_US(helper_close_file,HELPER_CLOSE_FILE)(int*); */
static PyObject *f2py_rout__xxdata_15_helper_close_file(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iunit = 0;
  PyObject *iunit_capi = Py_None;
  static char *capi_kwlist[] = {"iunit",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:_xxdata_15.helper_close_file",\
    capi_kwlist,&iunit_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iunit */
    f2py_success = int_from_pyobj(&iunit,iunit_capi,"_xxdata_15.helper_close_file() 1st argument (iunit) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iunit);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of iunit*/
  /* End of cleaning variable iunit */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of helper_close_file **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"xxdata_15",-1,{{-1}},0,(char *)F_FUNC_US(xxdata_15,XXDATA_15),(f2py_init_func)f2py_rout__xxdata_15_xxdata_15,doc_f2py_rout__xxdata_15_xxdata_15},
  {"helper_open_file",-1,{{-1}},0,(char *)F_FUNC_US(helper_open_file,HELPER_OPEN_FILE),(f2py_init_func)f2py_rout__xxdata_15_helper_open_file,doc_f2py_rout__xxdata_15_helper_open_file},
  {"helper_close_file",-1,{{-1}},0,(char *)F_FUNC_US(helper_close_file,HELPER_CLOSE_FILE),(f2py_init_func)f2py_rout__xxdata_15_helper_close_file,doc_f2py_rout__xxdata_15_helper_close_file},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_xxdata_15",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__xxdata_15(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_xxdata_15(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _xxdata_15_module = PyModule_Create(&moduledef);
#else
  m = _xxdata_15_module = Py_InitModule("_xxdata_15", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _xxdata_15 (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_xxdata_15' is auto-generated with f2py (version:2).\nFunctions:\n"
"  iz0,is,is1,esym,nptnl,nptn,nptnc,iptnla,iptna,iptnca,ncnct,icnctv,ncptn_stack,cptn_stack,lres,lptn,lcmt,lsup,nbsel,isela,cwavel,cfile,ctype,cindm,wavel,ispbr,isppr,isstgr,iszr,ita,ida,teta,teda,pec,pec_max,ncmt_stack,cmt_stack = xxdata_15(iunit,dsname,nstore,ntdim,nddim,ndptnl,ndptn,ndptnc,ndcnct,ndstack,ndcmt)\n"
"  iunit = helper_open_file(filename)\n"
"  helper_close_file(iunit)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _xxdata_15_error = PyErr_NewException ("_xxdata_15.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_xxdata_15");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
